/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/agents/': RouteRecordInfo<
      '/agents/',
      '/agents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/agents/[slug]/': RouteRecordInfo<
      '/agents/[slug]/',
      '/agents/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/agents/new/': RouteRecordInfo<
      '/agents/new/',
      '/agents/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/[slug]/': RouteRecordInfo<
      '/categories/[slug]/',
      '/categories/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/other/': RouteRecordInfo<
      '/other/',
      '/other',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/agents/index.vue': {
      routes:
        | '/agents/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/agents/[slug]/index.vue': {
      routes:
        | '/agents/[slug]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/agents/new/index.vue': {
      routes:
        | '/agents/new/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/categories/[slug]/index.vue': {
      routes:
        | '/categories/[slug]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/other/index.vue': {
      routes:
        | '/other/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
